"use client";
import { useState, useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import styles from "@/styles/Home.module.css";
import Ellipse from "../assets/images/ellipse.svg";
import Image1 from "../assets/images/home-image1.svg";
import Phone from "../assets/images/phone.svg";
import PhoneMobile from "../assets/images/Phone-mobile.svg";
import Card from "../components/Card";
import Padlock from "../assets/images/padlock.svg";
import CryptoCurrency from "../assets/images/crypto-currency.svg";
import {
  CardData,
  StepsData,
  HeroTexts,
  TestimonialData,
} from "../services/homedata";
import Rating from "@mui/material/Rating";
import Avatar from "@mui/material/Avatar";
import Customer from "../assets/images/customer.svg";
import CTAImage from "../assets/images/cta.svg";
import Bitcoin from "../assets/images/bitcoin.svg";
import Luna from "../assets/images/luna.svg";
import Eth from "../assets/images/eth.svg";
import TextShuffler from "../components/TextShuffler";
import ArrowBackSharpIcon from "@mui/icons-material/ArrowBackSharp";
import ArrowForwardSharpIcon from "@mui/icons-material/ArrowForwardSharp";
import EastIcon from "@mui/icons-material/East";
import { Button } from "../components/Button/Button";
import Footer from "@/components/Footer/Footer";
import { useRouter } from "next/router";
import { MOBILE_RESPONSIVE_BREAKPOINT } from "@/utils";

const Testimonial = ({ testimonial, onArrowClick }: any) => {
  const [value, setValue] = useState<number | null>(5);

  return (
    <div className={styles.testimonial}>
      <div style={{ marginBottom: 40 }}>
        <Rating
          name="simple-controlled"
          value={value}
          onChange={(event, newValue) => {
            setValue(newValue);
          }}
        />
      </div>
      <p className={styles.quote}>{testimonial.quote}</p>
      <div className={styles.customerInfoWrapper}>
        <div className={styles.customerInfo}>
          <div style={{ marginLeft: 16 }}>
            <p className={styles.customerName}> {testimonial.name}</p>
            <p className={styles.customerRole}> {testimonial.role}</p>
          </div>
        </div>
        <div className={styles.testimonialIconContainer}>
          <div
            className={styles.testimonialIconWrapper}
            onClick={() => onArrowClick("prev")}
          >
            <ArrowBackSharpIcon fontSize="medium" color="disabled" />
          </div>
          <div
            className={styles.testimonialIconWrapper}
            onClick={() => onArrowClick("next")}
          >
            <ArrowForwardSharpIcon fontSize="medium" color="disabled" />
          </div>
        </div>
      </div>
    </div>
  );
};

export default function Home() {
  const [current, setCurrent] = useState(0);
  const router = useRouter();
  const [isMobile, setIsMobile] = useState(false);

  const slide = (type: string) => {
    const last = TestimonialData.length - 1;
    const first = 0;
    let newCurrent;
    if (type === "prev") {
      if (first < current) {
        setCurrent(current - 1);
      }

      if (current === first) {
        setCurrent(last);
      }
    } else {
      if (type === "next") {
        if (last > current) {
          setCurrent(current + 1);
        }

        if (current === last) {
          setCurrent(first);
        }
      }
    }
  };

  useEffect(() => {
    const handleResize = () => {
      setIsMobile(window.innerWidth <= MOBILE_RESPONSIVE_BREAKPOINT);
    };
    handleResize();
    window.addEventListener("resize", handleResize);
    return () => {
      window.removeEventListener("resize", handleResize);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Luminary Exchange</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* TODO: REQUEST FOR A FAVICON */}
        <link rel="icon" href="/favicon.png" />
      </Head>
      <>
        <div className={styles.herosection}>
          <div>
            <Navbar />
            <div className={styles.content}>
              <h1 className={styles.title}>
                Easiest way to Buy, sell and trade
                <TextShuffler texts={HeroTexts} />
              </h1>
              <p className={styles.subTitle}>
                Give your team the autonomy they need with access to as many
                cards as they need. Authorise purchases with a click. Simple.
              </p>
              <div style={{ marginTop: 30 }}>
                <Button
                  color="secondary"
                  variant="contained"
                  sx={{
                    borderRadius: "29px",
                    textTransform: "capitalize",
                    width: "302px",
                    height: "61px",
                  }}
                  onClick={() => router.push("/signup")}
                >
                  Sign Up{" "}
                  <EastIcon style={{ marginLeft: 9, color: "#848484" }} />
                </Button>
              </div>
            </div>
          </div>
          <div
            style={{ position: "relative" }}
            data-aos="slide-up"
            data-aos-duration="2000"
            className={styles.ellipseSection}
          >
            <Image src={Ellipse} alt="Ellipse" className={styles.ellipse} />
            <div className={styles.herosectionImage}>
              <Image src={Image1} alt="image" />
            </div>
          </div>
        </div>
        <div className={styles.cardSection}>
          <div
            className={styles.cardSectionContent}
            data-aos="slide-up"
            data-aos-duration="2000"
          >
            <h1 className={styles.cardSectionTitle}>
              Everything you need at you fingertips
            </h1>
            <p className={styles.cardSectionSubTitle}>
              Has a variety of features that make it the best place to start
              trading
            </p>
          </div>
        </div>
        <div className={styles.cardContainer}>
          <div className={styles.cardWrapper}>
            {CardData.map((data) => (
              <div key={data.id} data-aos="ease-in" data-aos-duration="4000">
                <Card
                  image={data.image}
                  title={data.title}
                  subtitle={data.subtitle}
                />
              </div>
            ))}
          </div>
        </div>
        <div style={{ background: "#FFF8F1" }}>
          <div className={styles.stepsWrapper}>
            <div className={styles.leftSection}>
              <h1 className={styles.stepsTitle}>
                The Most Trusted Cryptocurrency Platform
              </h1>
              <div className={styles.stepsContent}>
                {StepsData.map((data) => (
                  <div key={data.id}>
                    <div className={styles.contentWrapper}>
                      <div className={styles.topContent}>
                        <span className={styles.stepsNumber}>
                          {data.number}
                        </span>
                        <h2 className={styles.stepsSubTitle}>{data.title}</h2>
                      </div>
                      <p className={styles.stepsInfo}>{data.subtitle}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className={styles.rightSection}>
              <Image
                src={isMobile ? PhoneMobile : Phone}
                alt="phone"
                className={styles.rightSection}
              />
            </div>
          </div>
          <div
            className={styles.moreInfo}
            // data-aos="flip-up"
            // data-aos-duration="2000"
          >
            <div className={styles.infoBox}>
              <Image
                src={Padlock}
                alt="padlock"
                style={{ width: isMobile ? "100px" : "" }}
              />
              <p style={{ width: 279 }}>Security from day one</p>
            </div>
            <div className={styles.infoBox}>
              <p>Smooth transactions</p>
              <Image
                src={CryptoCurrency}
                alt="padlock"
                style={{ width: isMobile ? "100px" : "" }}
              />
            </div>
          </div>
        </div>
        <div className={styles.testimonialSection}>
          <Testimonial
            testimonial={TestimonialData[current]}
            onArrowClick={slide}
          />
          <div
            className={styles.ctaSection}
            // data-aos="flip-up"
            // data-aos-duration="2000"
          >
            <div
              style={{ position: "relative" }}
              className={styles.ellipseSection}
            >
              <Image src={CTAImage} alt="cta" className={styles.imgCta} />
              <div className={styles.ctaImgText}>
                <h1 className={styles.ctaSectionTitle}>
                  Join over 4,000 crypto traders already growing with luminary
                </h1>

                <Image
                  src={Bitcoin}
                  alt="bitcoin"
                  className={styles.bitcoinImage}
                />
                <Image src={Luna} alt="luna" className={styles.lunaImage} />
                <Image src={Eth} alt="etherium" className={styles.ethImage} />
              </div>
            </div>
          </div>
        </div>
        <Footer />
      </>
    </>
  );
}
